In [43]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('df_bp1.csv')

C:\Users\sanch\AppData\Local\Temp\ipykernel_10212\2649927610.py:1: DtypeWarning: Columns (13,14,15,85,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('df_bp1.csv')


In [35]:
df.columns

Index(['date', 'dblheader_code', 'day_of_week', 'team_v', 'league_v',
       'game_no_v', 'team_h', 'league_h', 'game_no_h', 'runs_v',
       ...
       'SLG_30_h', 'SLG_30_v', 'OBS_30_h', 'OBS_30_v', 'SB_30_h', 'SB_30_v',
       'CS_30_h', 'CS_30_v', 'ERR_30_h', 'ERR_30_v'],
      dtype='object', length=194)

In [33]:
df.head(40)

date  dblheader_code day_of_week team_v league_v  game_no_v team_h  \
2245  19950616               0         Fri    SFN       NL         48    SLN   
2259  19950617               0         Sat    SFN       NL         49    SLN   
2268  19950618               0         Sun    MON       NL         50    CIN   
2269  19950618               0         Sun    ATL       NL         49    COL   
2271  19950618               0         Sun    FLO       NL         48    PHI   
2273  19950618               0         Sun    SFN       NL         50    SLN   
2275  19950619               0         Mon    KCA       AL         48    CAL   
2278  19950619               0         Mon    TEX       AL         50    DET   
2279  19950619               0         Mon    MIN       AL         50    OAK   
2280  19950619               0         Mon    ATL       NL         50    CIN   
2281  19950619               0         Mon    FLO       NL         49    COL   
2282  19950619               0         Mon    HOU       NL         48    MON   
2283  19950619               0         Mon    PHI       NL         49    NYN   
2286  19950619               0         Mon    LAN       NL         50    SLN   
2288  19950620               0         Tue    KCA       AL         49    CAL   
2291  19950620               0         Tue    TEX       AL         51    DET   
2292  19950620               0         Tue    MIN       AL         51    OAK   
2294  19950620               0         Tue    ATL       NL         51    CIN   
2295  19950620               0         Tue    FLO       NL         50    COL   
2296  19950620               0         Tue    HOU       NL         49    MON   
2297  19950620               0         Tue    PHI       NL         50    NYN   
2298  19950620               0         Tue    SFN       NL         52    PIT   
2299  19950620               0         Tue    CHN       NL         50    SDN   
2300  19950620               0         Tue    LAN       NL         51    SLN   
2302  19950621               0         Wed    KCA       AL         50    CAL   
2304  19950621               0         Wed    BOS       AL         50    CLE   
2305  19950621               0         Wed    TEX       AL         52    DET   
2306  19950621               0         Wed    MIN       AL         52    OAK   
2307  19950621               0         Wed    MIL       AL         49    TOR   
2308  19950621               0         Wed    ATL       NL         52    CIN   
2309  19950621               0         Wed    FLO       NL         51    COL   
2310  19950621               0         Wed    HOU       NL         50    MON   
2311  19950621               0         Wed    PHI       NL         51    NYN   
2312  19950621               0         Wed    SFN       NL         53    PIT   
2313  19950621               0         Wed    CHN       NL         51    SDN   
2314  19950621               0         Wed    LAN       NL         52    SLN   
2315  19950622               0         Thu    BOS       AL         51    BAL   
2317  19950622               0         Thu    MIL       AL         50    TOR   
2318  19950622               0         Thu    ATL       NL         53    CIN   
2319  19950622               0         Thu    CHN       NL         52    HOU   

     league_h  game_no_h  runs_v  ...  SLG_30_h  SLG_30_v  OBS_30_h  OBS_30_v  \
2245       NL         48       5  ...  0.388074  0.374275  0.708254  0.673735   
2259       NL         49       4  ...  0.390148  0.378378  0.712028  0.680975   
2268       NL         48       7  ...  0.436941  0.387695  0.785737  0.712428   
2269       NL         49       9  ...  0.458984  0.440276  0.796798  0.779244   
2271       NL         48       3  ...  0.355131  0.373412  0.690266  0.694399   
2273       NL         50       6  ...  0.380811  0.388088  0.699941  0.693718   
2275       AL         50       8  ...  0.470701  0.406489  0.841354  0.746987   
2278       AL         51       6  ...  0.442289  0.404150  0.799069  0.756413   


In [5]:
df.info(max_cols=200)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67355 entries, 0 to 67354
Data columns (total 194 columns):
 #    Column                Non-Null Count  Dtype  
---   ------                --------------  -----  
 0    date                  67355 non-null  int64  
 1    dblheader_code        67355 non-null  int64  
 2    day_of_week           67355 non-null  object 
 3    team_v                67355 non-null  object 
 4    league_v              67355 non-null  object 
 5    game_no_v             67355 non-null  int64  
 6    team_h                67355 non-null  object 
 7    league_h              67355 non-null  object 
 8    game_no_h             67355 non-null  int64  
 9    runs_v                67355 non-null  int64  
 10   runs_h                67355 non-null  int64  
 11   outs_total            67355 non-null  int64  
 12   day_night             67355 non-null  object 
 13   completion_info       54 non-null     object 
 14   forfeit_info          1 non-null      object 
 15   

In [6]:
df.season.value_counts().sort_index()

1994    1600
1995    2017
1996    2267
1997    2266
1998    2432
1999    2428
2000    2429
2001    2429
2002    2426
2003    2430
2004    2428
2005    2431
2006    2429
2007    2431
2008    2428
2009    2430
2010    2430
2011    2429
2012    2430
2013    2431
2014    2430
2015    2429
2016    2428
2017    2430
2018    2431
2019    2429
2020     898
2021    2429
2022    2430
Name: season, dtype: int64

In [7]:
hv_mean = df.home_victory.mean()
hv_mean

0.5373320466186623

In [8]:
df.run_diff.value_counts()

 1     11537
-1      7501
 2      6259
-2      5965
 3      4967
-3      4713
 4      3886
-4      3795
 5      2810
-5      2800
 6      2132
-6      2021
 7      1487
-7      1468
 8      1106
-8       975
 9       745
-9       690
 10      471
-10      465
 11      303
-11      277
 12      187
-12      168
-13      138
 13      124
 14       71
-14       70
 15       41
-15       37
-16       32
 16       26
 17       14
 0        12
-17       11
-18       10
 19        8
 18        8
-19        6
 21        6
-21        4
 20        3
-20        2
 22        1
-22        1
-27        1
-23        1
Name: run_diff, dtype: int64

In [9]:
df.outs_total.value_counts()

51     30597
54     28188
60      1323
53      1250
52      1134
       ...  
105        2
132        1
99         1
55         1
35         1
Name: outs_total, Length: 70, dtype: int64

In [10]:
df.home_victory[df.outs_total==53].mean()

0.9992

In [11]:
df.loc[(df.outs_total==53) & (df.home_victory!=1)]

date  dblheader_code day_of_week team_v league_v  game_no_v team_h  \
27337  20050915               0         Thu    SLN       NL        148    CHN   

      league_h  game_no_h  runs_v  ...  SLG_30_h  SLG_30_v  OBS_30_h  \
27337       NL        147       6  ...  0.444444   0.39569  0.766795   

       OBS_30_v SB_30_h SB_30_v CS_30_h  CS_30_v  ERR_30_h ERR_30_v  
27337  0.723061    12.0    20.0     6.0      5.0      15.0     23.0  

[1 rows x 194 columns]

In [12]:
df.game_no_h.value_counts().sort_index()

1      430
2      430
3      434
4      429
5      426
      ... 
159    375
160    389
161    388
162    362
163     13
Name: game_no_h, Length: 163, dtype: int64

In [13]:
df[['OBP_162_h','OBP_162_v', 'SLG_162_h','SLG_162_v']].isna().sum()

OBP_162_h    2675
OBP_162_v    2671
SLG_162_h    2675
SLG_162_v    2671
dtype: int64

In [14]:
df = df.dropna(subset=['OBP_162_h', 'OBP_162_v', 'SLG_162_h', 'SLG_162_v'])

In [15]:
df.isna().sum()

date              0
dblheader_code    0
day_of_week       0
team_v            0
league_v          0
                 ..
SB_30_v           0
CS_30_h           0
CS_30_v           0
ERR_30_h          0
ERR_30_v          0
Length: 194, dtype: int64

In [16]:
df.dropna(subset=['OBP_162_h','OBP_162_v',
            'SLG_162_h','SLG_162_v', 
            # 'OBP_30_h','OBP_30_v',
            # 'SLG_30_h','SLG_30_v',
            # 'game_no_h',
           ])

date  dblheader_code day_of_week team_v league_v  game_no_v team_h  \
2245   19950616               0         Fri    SFN       NL         48    SLN   
2259   19950617               0         Sat    SFN       NL         49    SLN   
2268   19950618               0         Sun    MON       NL         50    CIN   
2269   19950618               0         Sun    ATL       NL         49    COL   
2271   19950618               0         Sun    FLO       NL         48    PHI   
...         ...             ...         ...    ...      ...        ...    ...   
67350  20221005               0         Wed    KCA       AL        162    CLE   
67351  20221005               0         Wed    PHI       NL        162    HOU   
67352  20221005               0         Wed    ANA       AL        162    OAK   
67353  20221005               0         Wed    DET       AL        162    SEA   
67354  20221005               0         Wed    NYA       AL        162    TEX   

      league_h  game_no_h  runs_v  ...  SLG_30_h  SLG_30_v  OBS_30_h  \
2245        NL         48       5  ...  0.388074  0.374275  0.708254   
2259        NL         49       4  ...  0.390148  0.378378  0.712028   
2268        NL         48       7  ...  0.436941  0.387695  0.785737   
2269        NL         49       9  ...  0.458984  0.440276  0.796798   
2271        NL         48       3  ...  0.355131  0.373412  0.690266   
...        ...        ...     ...  ...       ...       ...       ...   
67350       AL        162       2  ...  0.396617  0.380435  0.720988   
67351       AL        162       2  ...  0.426036  0.431275  0.737570   
67352       AL        162       2  ...  0.354354  0.427734  0.634797   
67353       AL        162       4  ...  0.398374  0.394685  0.708220   
67354       AL        162       2  ...  0.367781  0.435259  0.630340   

       OBS_30_v SB_30_h SB_30_v CS_30_h  CS_30_v  ERR_30_h ERR_30_v  
2245   0.673735    16.0    33.0     8.0     12.0      22.0     28.0  
2259   0.680975    17.0    33.0     7.0     12.0      24.0     28.0  
2268   0.712428    46.0    27.0    11.0     10.0      18.0     17.0  
2269   0.779244    23.0    16.0    16.0     11.0      22.0     19.0  
2271   0.694399    11.0    16.0     7.0     12.0      23.0     21.0  
...         ...     ...     ...     ...      ...       ...      ...  
67350  0.683631    36.0    19.0     6.0     10.0      21.0     10.0  
67351  0.746681    19.0    19.0     5.0      8.0      12.0     11.0  
67352  0.735567    10.0    11.0     2.0      2.0      17.0     17.0  
67353  0.684473    15.0     8.0     6.0      4.0      21.0     16.0  
67354  0.762938    24.0    23.0    11.0      6.0      16.0     15.0  

[64265 rows x 194 columns]

# Model

In [17]:
#Drop empates
df = df[df.run_diff!=0]

In [18]:
df_train = df[(df.season>1995) & (df.season<=2020)]
#df_valid = df[(df.season>=2019) & (df.season<=2020)]
df_test = df[df.season>=2021]

In [19]:
X = ['OBP_162_h','OBP_162_v',
            'SLG_162_h','SLG_162_v', 
             'OBP_30_h','OBP_30_v',
             #'SLG_30_h','SLG_30_v',
           ]
target = 'home_victory'

In [20]:
X

['OBP_162_h', 'OBP_162_v', 'SLG_162_h', 'SLG_162_v', 'OBP_30_h', 'OBP_30_v']

In [21]:
X_train = df_train.loc[:,X]
X_test = df_test.loc[:,X]

y_train = df_train[target].to_numpy()
y_test = df_test[target].to_numpy()

In [22]:
X_train.shape, X_test.shape #X_valid.shape,

((58059, 6), (4859, 6))

In [23]:
y_train.shape, y_test.shape #y_valid.shape

((58059,), (4859,))

In [24]:
X_train.isna().sum()

OBP_162_h    0
OBP_162_v    0
SLG_162_h    0
SLG_162_v    0
OBP_30_h     0
OBP_30_v     0
dtype: int64

In [25]:
smote = SMOTE()

In [26]:
X_train_sm, y_train_sm = smote.fit_resample(X_train.to_numpy(), y_train)

In [27]:
X_train_sm

array([[0.34452154, 0.35479778, 0.44599179, 0.42715525, 0.34916447,
        0.32446809],
       [0.34019783, 0.32868624, 0.41456483, 0.40930744, 0.35762712,
        0.2749301 ],
       [0.3359426 , 0.32851173, 0.41391809, 0.41072689, 0.33508772,
        0.2995671 ],
       ...,
       [0.33591543, 0.30708325, 0.43395241, 0.37799523, 0.31713849,
        0.29933093],
       [0.3429075 , 0.32202441, 0.43729634, 0.43846115, 0.35388748,
        0.32466606],
       [0.33725631, 0.32445235, 0.41345827, 0.421933  , 0.34537048,
        0.31294777]])

In [28]:
forest = RandomForestClassifier()


In [29]:
forest.fit(X_train_sm, y_train_sm)

RandomForestClassifier()

In [30]:
forest.score(X_train_sm,y_train_sm)

1.0

In [31]:
forest.score(X_test.to_numpy(),y_test)

0.537353364889895

In [32]:
y_test

array([0, 0, 1, ..., 1, 1, 1], dtype=int64)

In [39]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [40]:
y_pred = model.predict(X_test)

In [41]:
y_pred

array([1, 1, 0, ..., 0, 1, 0], dtype=int64)

In [44]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 0.5540234616176168
